/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */
import type { ActivityLogResponseMetadata } from './activityLogResponseMetadata';
import type { ActivityLogResponseNewValues } from './activityLogResponseNewValues';
import type { ActivityLogResponseOldValues } from './activityLogResponseOldValues';

export interface ActivityLogResponse {
  entity_type: string;
  entity_id: string;
  entity_reference?: string | null;
  action: string;
  action_category?: string;
  old_values?: ActivityLogResponseOldValues;
  new_values?: ActivityLogResponseNewValues;
  changed_fields?: string[] | null;
  user_id?: string | null;
  user_role?: string | null;
  user_name?: string | null;
  metadata?: ActivityLogResponseMetadata;
  id: string;
  created_at: string;
}
