/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

export interface AttestationSubmitRequest {
  /**
     * @minLength 2
     * @maxLength 255
     */
  agent_nom: string;
}
