/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

export interface AttestationValidateRequest {
  /**
     * @minLength 2
     * @maxLength 255
     */
  chef_nom: string;
  signature_media_id?: string | null;
  empreinte_media_id?: string | null;
}
