/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

export interface AttestationSummary {
  id: string;
  reference: string;
  version: number;
  type: string;
  statut: string;
  date_etablissement?: string | null;
  date_expiration?: string | null;
}
