/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

export interface ClientCreateRequest {
  type?: string;
  nom?: string | null;
  prenom?: string | null;
  nom_entreprise?: string | null;
  cni_numero?: string | null;
  cni_date?: string | null;
  cni_lieu?: string | null;
  telephone?: string | null;
  email?: string | null;
  adresse?: string | null;
  profession?: string | null;
  employeur?: string | null;
  naissance_date?: string | null;
  naissance_lieu?: string | null;
  nationalite?: string | null;
  actif?: boolean;
}
