/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

export interface ClientResponse {
  id: string;
  type?: string | null;
  nom?: string | null;
  prenom?: string | null;
  nom_entreprise?: string | null;
  cni_numero?: string | null;
  telephone?: string | null;
  email?: string | null;
  adresse?: string | null;
  professionnel?: string | null;
  created_at?: unknown | null;
  updated_at?: unknown | null;
}
