/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

export interface CreateUserRequest {
  email: string;
  password: string;
  full_name: string;
  access_level?: string;
  role?: string | null;
  poste?: string | null;
  department?: string | null;
  phone?: string | null;
}
