/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

export interface DuplicateCheckParams {
  village_id: string;
  lotissement_id: string;
  ilot_id: string;
  numero_lot: string;
  exclude_lot_id?: string | null;
}
