/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

export interface EmployeeResponse {
  id: string;
  nom: string;
  prenom: string;
  poste?: string | null;
  email?: string | null;
  department?: string | null;
  telephone?: string | null;
  salaire?: number | null;
  date_embauche?: string | null;
  statut?: string;
  notes?: string | null;
  photo_url?: string | null;
  created_at?: unknown | null;
  updated_at?: unknown | null;
}
