/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

export type ExportLotsApiV1FoncierLotsExportPostParams = {
village_id?: string | null;
statut?: string | null;
};
