/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

export interface FinanceResponse {
  id: string;
  reference: string;
  montant: number;
  type?: string | null;
  type_transaction?: string | null;
  categorie?: string | null;
  date_transaction?: string | null;
  mode_paiement?: string | null;
  description?: string | null;
  client_id?: string | null;
  project_id?: string | null;
  statut?: string | null;
  created_at?: unknown | null;
  updated_at?: unknown | null;
}
