/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

export interface IlotResponse {
  /**
     * @minLength 1
     * @maxLength 50
     */
  numero: string;
  description?: string | null;
  superficie_totale?: number | null;
  id: string;
  lotissement_id: string;
  created_at: string;
  updated_at: string;
  created_by?: string | null;
  updated_by?: string | null;
}
