/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

export type ListMediaUsageApiV1MediaUsageGetParams = {
media_id?: string | null;
entity_type?: string | null;
entity_id?: string | null;
usage_type?: string | null;
};
