/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */
import type { LotCreateGpsBornage } from './lotCreateGpsBornage';

export interface LotCreate {
  /**
     * @minLength 1
     * @maxLength 50
     */
  numero_lot: string;
  /** @exclusiveMinimum 0 */
  superficie: number;
  prix?: number | null;
  /** @pattern ^(actif|vendu|litige|reserve|annule|archive)$ */
  statut?: string;
  proprietaire_client_id?: string | null;
  proprietaire_nom?: string | null;
  proprietaire_prenom?: string | null;
  proprietaire_naissance_date?: string | null;
  proprietaire_naissance_lieu?: string | null;
  proprietaire_cni_numero?: string | null;
  proprietaire_cni_date?: string | null;
  proprietaire_cni_lieu?: string | null;
  proprietaire_profession?: string | null;
  proprietaire_telephone?: string | null;
  proprietaire_email?: string | null;
  gps_lat?: number | null;
  gps_lng?: number | null;
  gps_precision?: number | null;
  gps_bornage?: LotCreateGpsBornage;
  chef_village?: string | null;
  arrete_prefectoral?: string | null;
  arrete_date?: string | null;
  publier_sur_vitrine?: boolean;
  date_cession?: string | null;
  prix_cession?: number | null;
  notes?: string | null;
  ilot_id: string;
}
