/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */
import type { LotUpdateGpsBornage } from './lotUpdateGpsBornage';

export interface LotUpdate {
  numero_lot?: string | null;
  superficie?: number | null;
  prix?: number | null;
  statut?: string | null;
  proprietaire_client_id?: string | null;
  proprietaire_nom?: string | null;
  proprietaire_prenom?: string | null;
  proprietaire_naissance_date?: string | null;
  proprietaire_naissance_lieu?: string | null;
  proprietaire_cni_numero?: string | null;
  proprietaire_cni_date?: string | null;
  proprietaire_cni_lieu?: string | null;
  proprietaire_profession?: string | null;
  proprietaire_telephone?: string | null;
  proprietaire_email?: string | null;
  gps_lat?: number | null;
  gps_lng?: number | null;
  gps_precision?: number | null;
  gps_bornage?: LotUpdateGpsBornage;
  chef_village?: string | null;
  arrete_prefectoral?: string | null;
  arrete_date?: string | null;
  publier_sur_vitrine?: boolean | null;
  date_cession?: string | null;
  prix_cession?: number | null;
  notes?: string | null;
}
