/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

export interface MediaUsageCreateRequest {
  media_id: string;
  entity_type: string;
  entity_id?: string | null;
  usage_type: string;
  label?: string;
}
