/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

export interface MediaResponse {
  id: string;
  filename: string;
  original_name: string;
  url: string;
  thumbnail_url?: string | null;
  category: string;
  uploaded_by?: string | null;
  upload_date?: unknown | null;
  size: number;
  type: string;
  alt_text: string;
  description: string;
  tags: string[];
  is_brand_asset: boolean;
  brand_asset_type?: string | null;
  created_at?: unknown | null;
  updated_at?: unknown | null;
  deleted_at?: unknown | null;
  deleted_by?: string | null;
  width?: number | null;
  height?: number | null;
}
