/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

export interface PaginatedResponse {
  items: unknown[];
  total: number;
  page: number;
  page_size: number;
  total_pages: number;
}
