/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

export interface ProductResponse {
  id: string;
  designation?: string | null;
  nom?: string | null;
  categorie?: string | null;
  prix_unitaire?: number | null;
  stock_actuel?: number | null;
  stock_minimum?: number | null;
  unite?: string | null;
  description?: string | null;
  image_url?: string | null;
  created_at?: unknown | null;
  updated_at?: unknown | null;
}
