/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

export type SearchAuditApiV1FoncierAuditGetParams = {
entity_type?: string | null;
entity_id?: string | null;
action?: string | null;
user_id?: string | null;
date_from?: string | null;
date_to?: string | null;
/**
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 500
 */
page_size?: number;
};
