/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

export type SearchLotsApiV1FoncierLotsGetParams = {
search?: string | null;
statut?: string | null;
village_id?: string | null;
lotissement_id?: string | null;
ilot_id?: string | null;
/**
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 200
 */
page_size?: number;
};
