/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */
import type { SettingsAuditRowUserProfiles } from './settingsAuditRowUserProfiles';

export interface SettingsAuditRow {
  id: string;
  setting_key: string;
  old_value?: string | null;
  new_value?: string | null;
  changed_by?: string | null;
  changed_at: string;
  user_profiles?: SettingsAuditRowUserProfiles;
}
