/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

export interface SupplierCreateRequest {
  nom: string;
  email?: string | null;
  telephone?: string | null;
  adresse?: string | null;
  produits_fournis?: string | null;
  statut?: string;
  notes?: string | null;
}
