/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

export interface SyncStatusResponse {
  pending: number;
  last_sync?: string | null;
  last_error?: string | null;
  queue_size: number;
}
