/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

export interface TenantCreateRequest {
  party_id: string;
  property_id?: string | null;
  contract_id?: string | null;
}
