/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */
import type { ActivityLogResponse } from './activityLogResponse';

export interface TimelineResponse {
  entity_type: string;
  entity_id: string;
  entity_reference: string;
  events: ActivityLogResponse[];
}
