/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

export interface UserResponse {
  id: string;
  email: string;
  full_name: string;
  role: string;
  access_level: string;
  poste?: string | null;
  department?: string | null;
  phone?: string | null;
  avatar_url?: string | null;
}
