/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

export interface VillageStats {
  village_id: string;
  village_nom: string;
  village_code: string;
  total_lots: number;
  lots_actifs: number;
  lots_vendus: number;
  lots_litiges: number;
  lots_reserves: number;
  lots_archives: number;
  superficie_totale: number;
  superficie_vendue: number;
  nb_attestations: number;
  nb_attestations_validees: number;
  ca_total: number;
}
