/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */
import type { VillageStats } from './villageStats';
import type { VillageWithStatsConfigJsonb } from './villageWithStatsConfigJsonb';

export interface VillageWithStats {
  /**
     * @minLength 2
     * @maxLength 255
     */
  nom: string;
  /**
     * @minLength 2
     * @maxLength 10
     * @pattern ^[A-Z0-9]+$
     */
  code: string;
  region?: string | null;
  departement?: string | null;
  commune?: string | null;
  chef_nom?: string | null;
  chef_telephone?: string | null;
  chef_email?: string | null;
  arrete_prefectoral?: string | null;
  arrete_date?: string | null;
  lieu_signature?: string | null;
  nom_signataire?: string | null;
  /** @pattern ^#[0-9a-fA-F]{6}$ */
  primary_color?: string;
  /** @pattern ^#[0-9a-fA-F]{6}$ */
  secondary_color?: string;
  /** @pattern ^(standard|compact|detailed)$ */
  layout_preference?: string;
  config_jsonb?: VillageWithStatsConfigJsonb;
  actif?: boolean;
  id: string;
  created_at: string;
  updated_at: string;
  created_by?: string | null;
  updated_by?: string | null;
  stats?: VillageStats | null;
}
