project_id = "somagro-erp"

[api]
port = 55321

[db]
port = 55322
shadow_port = 55320
major_version = 17

[studio]
port = 55323
api_url = "http://127.0.0.1"

[inbucket]
port = 55324

[auth]
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["http://127.0.0.1:3000"]
