"""Ensure the legacy property fields declared by the ORM exist.

Revision ID: 030_restore_property_orm_compat_columns
Revises: 029_auth_password_lifecycle

These nullable compatibility fields were present in an earlier autogenerated
revision but are absent from the current clean migration path. Existing EGS
databases may already contain them, so the upgrade is idempotent. The
downgrade intentionally preserves these fields because this revision cannot
distinguish columns it added from columns that predated it.
"""

from alembic import op


revision = "030_restore_property_orm_compat_columns"
down_revision = "029_auth_password_lifecycle"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        "ALTER TABLE public.properties "
        "ADD COLUMN IF NOT EXISTS proprietaire VARCHAR"
    )
    op.execute(
        "ALTER TABLE public.properties "
        "ADD COLUMN IF NOT EXISTS valeur NUMERIC(12, 2)"
    )
    op.execute(
        "ALTER TABLE public.properties "
        "ADD COLUMN IF NOT EXISTS loyer_mensuel NUMERIC(10, 2)"
    )
    op.execute(
        "ALTER TABLE public.properties "
        "ADD COLUMN IF NOT EXISTS cover_image_url VARCHAR"
    )


def downgrade() -> None:
    # Do not drop columns that may have existed before this revision.
    pass
