/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */
import type { UserResponse } from './userResponse';

export interface AuthTokenResponse {
  access_token: string;
  refresh_token: string;
  token_type?: string;
  user: UserResponse;
}
