/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */
import type { CampaignUpdateRequestKpiCibles } from './campaignUpdateRequestKpiCibles';
import type { CampaignUpdateRequestSegmentFilter } from './campaignUpdateRequestSegmentFilter';
import type { CampaignUpdateRequestTemplateContent } from './campaignUpdateRequestTemplateContent';

export interface CampaignUpdateRequest {
  nom?: string | null;
  description?: string | null;
  type_campagne?: string | null;
  budget?: number | null;
  date_debut?: string | null;
  date_fin?: string | null;
  canaux?: string[] | null;
  kpi_cibles?: CampaignUpdateRequestKpiCibles;
  template_content?: CampaignUpdateRequestTemplateContent;
  segment_filter?: CampaignUpdateRequestSegmentFilter;
  statut?: string | null;
}
