/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

export type CheckLotExistsApiV1FoncierLotsExistsGetParams = {
reference?: string | null;
numero_lot?: string | null;
ilot_id?: string | null;
};
