/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

export interface ClientResponse {
  id: string;
  nom: string;
  prenom: string;
  telephone?: string | null;
  email?: string | null;
  adresse?: string | null;
  /** @pattern ^(particulier|entreprise|promoteur_immobilier|institution)$ */
  type_client: string;
  notes?: string | null;
  created_at: string;
  updated_at: string;
}
