/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */
import type { ConflictResolutionRequestMergedData } from './conflictResolutionRequestMergedData';

export interface ConflictResolutionRequest {
  /** @pattern ^(local|server|merge)$ */
  resolution: string;
  merged_data?: ConflictResolutionRequestMergedData;
}
