/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

export type DeleteFinanceEntryApiV1FinanceFinanceIdDelete200 = {[key: string]: string};
