/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */
import type { EntityResponseEntityMetadata } from './entityResponseEntityMetadata';

export interface EntityResponse {
  /** @pattern ^(client|employee|supplier|partner|lead|visitor|user)$ */
  type: string;
  subtype?: string | null;
  /** @pattern ^(active|inactive|archived|pending|onboarding)$ */
  status?: string;
  display_name?: string | null;
  first_name?: string | null;
  last_name?: string | null;
  company_name?: string | null;
  id_document_type?: string | null;
  id_document_number?: string | null;
  id_document_date?: string | null;
  id_document_place?: string | null;
  phone?: string | null;
  email?: string | null;
  address?: string | null;
  profession?: string | null;
  employer?: string | null;
  birth_date?: string | null;
  birth_place?: string | null;
  nationality?: string | null;
  entity_metadata?: EntityResponseEntityMetadata;
  id: string;
  created_at: string;
  updated_at: string;
}
