/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

export type ExportAuditCsvApiV1FoncierAuditExportCsvPostParams = {
entity_type?: string | null;
entity_id?: string | null;
date_from?: string | null;
date_to?: string | null;
};
