/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */
import type { LeadCaptureRequestChannelsOptin } from './leadCaptureRequestChannelsOptin';

export interface LeadCaptureRequest {
  phone: string;
  first_name?: string | null;
  last_name?: string | null;
  email?: string | null;
  source?: string;
  source_page?: string | null;
  source_form?: string | null;
  consent_text?: string | null;
  channels_optin?: LeadCaptureRequestChannelsOptin;
}
