/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

export interface LeaseContractStatsResponse {
  total_contracts: number;
  actif: number;
  termine: number;
  resilie: number;
  renouvele: number;
  en_attente: number;
  total_monthly_revenue: number;
  total_deposits_held: number;
}
