/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

export interface LeaseContractUpdate {
  property_id?: string | null;
  locataire_id?: string | null;
  date_debut?: string | null;
  date_fin?: string | null;
  loyer_mensuel?: number | null;
  charges_mensuelles?: number | null;
  depot_garantie?: number | null;
  statut?: string | null;
  reference?: string | null;
  notes?: string | null;
  commission_rate?: number | null;
  jour_echeance?: number | null;
}
