/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

export type ListPaymentsApiV1ImmobilierApiV1ImmobilierPaymentsGetParams = {
/**
 * Recherche texte (référence, notes, mois)
 */
search?: string | null;
/**
 * Filtrer par propriété
 */
property_id?: string | null;
/**
 * Filtrer par bail
 */
contract_id?: string | null;
/**
 * Filtrer par locataire
 */
locataire_entity_id?: string | null;
/**
 * Filtrer par statut
 */
statut?: string | null;
/**
 * Filtrer par mois concerné (YYYY-MM)
 */
mois_concerne?: string | null;
/**
 * Date de début
 */
date_from?: string | null;
/**
 * Date de fin
 */
date_to?: string | null;
/**
 * @minimum 1
 * @maximum 200
 */
limit?: number;
/**
 * @minimum 0
 */
offset?: number;
/**
 * @pattern ^(date_paiement|created_at|montant|statut|mois_concerne)$
 */
order_by?: string;
descending?: boolean;
include_relations?: boolean;
};
