/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

export interface LotissementUpdate {
  nom?: string | null;
  code?: string | null;
  description?: string | null;
  superficie_totale?: number | null;
  nombre_lots_prevus?: number | null;
  arrete_lotissement?: string | null;
  arrete_date?: string | null;
}
