/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

export interface LotissementCreate {
  /**
     * @minLength 2
     * @maxLength 255
     */
  nom: string;
  code?: string | null;
  description?: string | null;
  superficie_totale?: number | null;
  nombre_lots_prevus?: number | null;
  arrete_lotissement?: string | null;
  arrete_date?: string | null;
  village_id?: string | null;
}
