/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

export interface MediaDeleteResponse {
  status: string;
  deleted_at?: unknown | null;
  media_id: string;
}
