/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */
import type { PageLayoutRowLayoutJson } from './pageLayoutRowLayoutJson';

export interface PageLayoutRow {
  page_slug: string;
  layout_json?: PageLayoutRowLayoutJson;
  is_published?: boolean;
  page_name?: string | null;
  seo_title?: string | null;
  seo_description?: string | null;
  seo_keywords?: string[] | null;
  og_image_media_id?: string | null;
}
