/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */
import type { RentPaymentResponse } from './rentPaymentResponse';

export interface PaginatedRentPaymentResponse {
  items: RentPaymentResponse[];
  total: number;
  page: number;
  page_size: number;
  total_pages: number;
}
