/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

export interface PartyToEntityMapping {
  party_id: string;
  entity_id: string;
  party_type: string;
}
