/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

export interface PropertyCreate {
  /** @pattern ^(studio|chambre|chambre-salon|appartement|terrain|magasin|bureau|villa)$ */
  type_bien: string;
  adresse?: string | null;
  proprietaire_name?: string | null;
  valeur?: number | null;
  loyer_mensuel?: number | null;
  charges_mensuelles?: number | null;
  statut?: string | null;
  description?: string | null;
  cover_image_url?: string | null;
}
