/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

export interface PropertyStatsResponse {
  total_properties: number;
  disponible: number;
  loue: number;
  en_vente: number;
  vendu: number;
  en_travaux: number;
  total_monthly_rent: number;
  occupancy_rate: number;
}
