/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

export interface RentPaymentUpdate {
  locataire_id?: string | null;
  property_id?: string | null;
  contract_id?: string | null;
  montant?: number | null;
  date_paiement?: string | null;
  date_echeance?: string | null;
  mois_concerne?: string | null;
  mode_paiement?: string | null;
  statut?: string | null;
  notes?: string | null;
  reference?: string | null;
  last_document_type?: string | null;
  last_document_at?: string | null;
  last_document_by?: string | null;
}
