/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

export interface RentPaymentCreate {
  locataire_id: string;
  property_id: string;
  contract_id: string;
  /** @minimum 0 */
  montant: number;
  date_paiement: string;
  date_echeance?: string | null;
  mois_concerne: string;
  mode_paiement?: string | null;
  statut?: string | null;
  notes?: string | null;
  reference?: string | null;
  last_document_type?: string | null;
  last_document_at?: string | null;
  last_document_by?: string | null;
}
