/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

export type SearchTenantsSuggestApiV1TenantsSearchSuggestGetParams = {
/**
 * @minLength 2
 * @maxLength 100
 */
q: string;
/**
 * @minimum 1
 * @maximum 50
 */
limit?: number;
};
