/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

export type SearchAttestationsApiV1FoncierAttestationsGetParams = {
lot_id?: string | null;
statut?: string | null;
/**
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 200
 */
page_size?: number;
};
