/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */
import type { SettingsOperationResponseData } from './settingsOperationResponseData';

/**
 * Réponse standard pour opérations settings
 */
export interface SettingsOperationResponse {
  status?: string;
  message: string;
  data?: SettingsOperationResponseData;
}
