/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */
import type { SiteRealisationRowMetadataJson } from './siteRealisationRowMetadataJson';

export interface SiteRealisationRow {
  id?: string | null;
  reference?: string | null;
  titre?: string | null;
  description?: string | null;
  description_courte?: string | null;
  type_realisation?: string | null;
  statut?: string | null;
  localisation?: string | null;
  ville?: string | null;
  surface?: number | null;
  budget_previsionnel?: number | null;
  budget_reel?: number | null;
  date_debut?: string | null;
  date_fin_prevue?: string | null;
  date_fin_reelle?: string | null;
  chef_projet_id?: string | null;
  equipe?: unknown[] | null;
  photos?: unknown[] | null;
  documents?: unknown[] | null;
  publier_vitrine?: boolean;
  ordre_affichage?: number;
  tags?: string[] | null;
  metadata_json?: SiteRealisationRowMetadataJson;
  created_at?: string | null;
  updated_at?: string | null;
}
