/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

export interface TaskResponse {
  id: string;
  titre: string;
  description?: string | null;
  employee_id?: string | null;
  project_id?: string | null;
  statut?: string | null;
  priorite?: string | null;
  date_debut?: unknown | null;
  date_echeance?: unknown | null;
  created_at?: unknown | null;
  updated_at?: unknown | null;
}
