/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

export interface TenantResponse {
  id: string;
  entity_id: string;
  nom?: string | null;
  prenom?: string | null;
  nom_entreprise?: string | null;
  telephone?: string | null;
  email?: string | null;
  adresse?: string | null;
  property_id?: string | null;
  contract_id?: string | null;
  created_at?: string | null;
  updated_at?: string | null;
}
