/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

export type VerifyAttestationApiAttestationsVerifyGetParams = {
ref?: string | null;
control?: string | null;
hash?: string | null;
};
