/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */
import type { VillageUpdateConfigJsonb } from './villageUpdateConfigJsonb';

export interface VillageUpdate {
  nom?: string | null;
  code?: string | null;
  region?: string | null;
  departement?: string | null;
  commune?: string | null;
  chef_nom?: string | null;
  chef_telephone?: string | null;
  chef_email?: string | null;
  arrete_prefectoral?: string | null;
  arrete_date?: string | null;
  lieu_signature?: string | null;
  nom_signataire?: string | null;
  primary_color?: string | null;
  secondary_color?: string | null;
  layout_preference?: string | null;
  config_jsonb?: VillageUpdateConfigJsonb;
  actif?: boolean | null;
}
