/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

export interface VitrineLotRow {
  id?: string | null;
  lot_id?: string | null;
  property_id?: string | null;
  titre?: string | null;
  description?: string | null;
  prix?: number | null;
  surface?: number | null;
  localisation?: string | null;
  photos?: unknown[] | null;
  publier?: boolean;
  ordre?: number;
  tags?: string[] | null;
  reference?: string | null;
  village?: string | null;
  quartier?: string | null;
  commune?: string | null;
  departement?: string | null;
  region?: string | null;
  superficie?: number | null;
  prix_vente?: number | null;
  statut?: string | null;
  documents?: string | null;
  caracteristiques?: string[] | null;
  image_url?: string | null;
  image_alt?: string | null;
  contact_phone?: string | null;
  contact_email?: string | null;
  publier_sur_vitrine?: boolean;
  ordre_affichage?: number;
  notes?: string | null;
  created_by?: string | null;
  updated_by?: string | null;
  created_at?: string | null;
  updated_at?: string | null;
}
