/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */
import type { AttestationVerificationResponseLot } from './attestationVerificationResponseLot';
import type { AttestationVerificationResponseProprietaire } from './attestationVerificationResponseProprietaire';
import type { AttestationVerificationResponseVillage } from './attestationVerificationResponseVillage';

export interface AttestationVerificationResponse {
  reference: string;
  statut: string;
  date_etablissement?: string | null;
  date_expiration?: string | null;
  lot: AttestationVerificationResponseLot;
  village: AttestationVerificationResponseVillage;
  proprietaire: AttestationVerificationResponseProprietaire;
  verifie_le: string;
  authentique: boolean;
}
