/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */
import type { AttestationUpdateGpsPoints } from './attestationUpdateGpsPoints';
import type { TemoinCreate } from './temoinCreate';

export interface AttestationUpdate {
  type?: string | null;
  statut?: string | null;
  date_etablissement?: string | null;
  date_expiration?: string | null;
  mode_acquisition?: string | null;
  historique_possession?: string | null;
  domicile?: string | null;
  cedant_nom?: string | null;
  cedant_prenom?: string | null;
  cedant_cni_numero?: string | null;
  cedant_telephone?: string | null;
  cedant_domicile?: string | null;
  limites_nord?: string | null;
  limites_sud?: string | null;
  limites_est?: string | null;
  limites_ouest?: string | null;
  gps_lat?: number | null;
  gps_lng?: number | null;
  gps_precision?: number | null;
  gps_points?: AttestationUpdateGpsPoints;
  registre_volume?: string | null;
  registre_page?: number | null;
  registre_ligne?: number | null;
  numero_enregistrement?: string | null;
  validation_agent_nom?: string | null;
  validation_chef_nom?: string | null;
  temoins?: TemoinCreate[] | null;
}
