/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */
import type { AttestationResponseGpsPoints } from './attestationResponseGpsPoints';
import type { TemoinResponse } from './temoinResponse';

export interface AttestationResponse {
  /** @pattern ^(standard|cession|succession|mutation)$ */
  type?: string;
  /** @pattern ^(brouillon|soumis|valide|archive|revoque|expire|annule)$ */
  statut?: string;
  date_etablissement?: string | null;
  date_expiration?: string | null;
  mode_acquisition?: string | null;
  historique_possession?: string | null;
  domicile?: string | null;
  cedant_nom?: string | null;
  cedant_prenom?: string | null;
  cedant_cni_numero?: string | null;
  cedant_telephone?: string | null;
  cedant_domicile?: string | null;
  limites_nord?: string | null;
  limites_sud?: string | null;
  limites_est?: string | null;
  limites_ouest?: string | null;
  gps_lat?: number | null;
  gps_lng?: number | null;
  gps_precision?: number | null;
  gps_points?: AttestationResponseGpsPoints;
  registre_volume?: string | null;
  registre_page?: number | null;
  registre_ligne?: number | null;
  numero_enregistrement?: string | null;
  validation_agent_nom?: string | null;
  validation_chef_nom?: string | null;
  temoins?: TemoinResponse[];
  id: string;
  lot_id: string;
  reference: string;
  version: number;
  proprietaire_client_id?: string | null;
  qr_payload?: string | null;
  signature_numerique?: string | null;
  hash_sha256?: string | null;
  control_number?: string | null;
  signature_nonce?: string | null;
  signature_issued_at?: string | null;
  validation_agent_id?: string | null;
  validation_agent_date?: string | null;
  validation_chef_id?: string | null;
  validation_chef_date?: string | null;
  proprietaire_photo_media_id?: string | null;
  proprietaire_empreinte_media_id?: string | null;
  chef_signature_manuscrite_requise?: boolean;
  chef_signature_media_id?: string | null;
  chef_empreinte_media_id?: string | null;
  temoin_empreinte_media_ids?: string[];
  revoke_reason?: string | null;
  revoked_at?: string | null;
  revoked_by?: string | null;
  pdf_media_id?: string | null;
  pdf_generated_at?: string | null;
  printed_by?: string | null;
  printed_at?: string | null;
  print_count?: number;
  created_by?: string | null;
  created_at: string;
  updated_at: string;
  client_updated_at?: string | null;
  last_modified_device_id?: string | null;
  deleted_at?: string | null;
}
