/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

export interface BodyUploadMediaApiV1MediaPost {
  file: Blob;
  category?: string;
  alt_text?: string;
  description?: string;
  tags?: string | null;
}
