/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */
import type { CampaignCreateRequestKpiCibles } from './campaignCreateRequestKpiCibles';
import type { CampaignCreateRequestSegmentFilter } from './campaignCreateRequestSegmentFilter';
import type { CampaignCreateRequestTemplateContent } from './campaignCreateRequestTemplateContent';

export interface CampaignCreateRequest {
  nom: string;
  description?: string | null;
  type_campagne?: string;
  budget?: number | null;
  date_debut?: string | null;
  date_fin?: string | null;
  canaux?: string[];
  kpi_cibles?: CampaignCreateRequestKpiCibles;
  template_content?: CampaignCreateRequestTemplateContent;
  segment_filter?: CampaignCreateRequestSegmentFilter;
}
