/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

export type CheckDuplicateApiV1EntitiesCheckDuplicateGetParams = {
/**
 * Type document
 */
id_document_type?: string | null;
/**
 * Numéro document
 */
id_document_number?: string | null;
/**
 * Email
 */
email?: string | null;
/**
 * Téléphone
 */
phone?: string | null;
/**
 * ID à exclure de la vérification
 */
exclude_id?: string | null;
};
