/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

export interface ClientUpdateRequest {
  type_client?: string | null;
  nom?: string | null;
  prenom?: string | null;
  telephone?: string | null;
  email?: string | null;
  adresse?: string | null;
  notes?: string | null;
  nom_entreprise?: string | null;
  profession?: string | null;
  employeur?: string | null;
  naissance_date?: string | null;
  naissance_lieu?: string | null;
  nationalite?: string | null;
  actif?: boolean | null;
}
