/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */
import type { EntityCreate } from './entityCreate';

export interface EntityBulkCreate {
  items: EntityCreate[];
}
