/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

/**
 * Mise à jour partielle - tous les champs optionnels.
 */
export interface FinanceUpdateRequest {
  type_transaction?: string | null;
  categorie?: string | null;
  montant?: number | null;
  date_transaction?: string | null;
  mode_paiement?: string | null;
  description?: string | null;
  client_id?: string | null;
  project_id?: string | null;
  statut?: string | null;
}
