/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

/**
 * Schéma de création d'une transaction
 */
export interface FinanceCreateRequest {
  reference: string;
  montant: number;
  type_transaction?: string | null;
  categorie?: string | null;
  date_transaction?: string | null;
  mode_paiement?: string | null;
  description?: string | null;
  client_id?: string | null;
  project_id?: string | null;
  statut?: string;
}
