/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

export type GetLogsApiV1DashboardLogsGetParams = {
/**
 * @maximum 1000
 * @exclusiveMinimum 0
 */
lines?: number;
};
