/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

export interface ImmobilierResponse {
  id: string;
  titre: string;
  ville?: string | null;
  prix?: number | null;
  created_at?: unknown | null;
  updated_at?: unknown | null;
}
