/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

export interface ImmobilierCreateRequest {
  titre: string;
  ville?: string | null;
  prix?: number | null;
}
