/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

export interface LeadUpdateRequest {
  last_name?: string | null;
  first_name?: string | null;
  phone?: string | null;
  email?: string | null;
  source?: string | null;
  campagne_id?: string | null;
  statut?: string | null;
  assigned_to?: string | null;
  notes?: string | null;
}
