/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

export interface LeaseContractCreate {
  property_id: string;
  locataire_id: string;
  date_debut: string;
  date_fin?: string | null;
  /** @minimum 0 */
  loyer_mensuel: number;
  charges_mensuelles?: number | null;
  depot_garantie?: number | null;
  statut?: string | null;
  reference?: string | null;
  notes?: string | null;
  /**
     * @minimum 0
     * @maximum 100
     */
  commission_rate?: number;
  /**
     * @minimum 1
     * @maximum 28
     */
  jour_echeance?: number;
}
