/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */
import type { LeaseContractResponseLocataire } from './leaseContractResponseLocataire';
import type { LeaseContractResponseProperty } from './leaseContractResponseProperty';

export interface LeaseContractResponse {
  property_id?: string | null;
  locataire_id?: string | null;
  date_debut?: string | null;
  date_fin?: string | null;
  loyer_mensuel?: number | null;
  charges_mensuelles?: number | null;
  depot_garantie?: number | null;
  statut?: string | null;
  reference?: string | null;
  notes?: string | null;
  /**
     * @minimum 0
     * @maximum 100
     */
  commission_rate?: number;
  /**
     * @minimum 1
     * @maximum 28
     */
  jour_echeance?: number;
  id: string;
  created_at: string;
  updated_at: string;
  created_by?: string | null;
  updated_by?: string | null;
  deleted_at?: string | null;
  property?: LeaseContractResponseProperty;
  locataire?: LeaseContractResponseLocataire;
}
