/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

export type ListFinanceEntriesApiV1FinanceGetParams = {
/**
 * Nombre max de résultats
 * @minimum 1
 * @maximum 2000
 */
limit?: number;
/**
 * Décalage pour pagination
 * @minimum 0
 */
offset?: number;
};
