/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

export type ListSettingsAuditApiV1SettingsAuditGetParams = {
/**
 * @minimum 1
 * @maximum 500
 */
limit?: number;
};
