/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

export type ListContractsApiV1ImmobilierApiV1ImmobilierContractsGetParams = {
/**
 * Recherche texte (référence, notes)
 */
search?: string | null;
/**
 * Filtrer par propriété
 */
property_id?: string | null;
/**
 * Filtrer par locataire
 */
locataire_entity_id?: string | null;
/**
 * Filtrer par statut
 */
statut?: string | null;
/**
 * @minimum 1
 * @maximum 200
 */
limit?: number;
/**
 * @minimum 0
 */
offset?: number;
/**
 * @pattern ^(created_at|updated_at|date_debut|statut|reference|loyer_mensuel)$
 */
order_by?: string;
descending?: boolean;
include_relations?: boolean;
};
