/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

export type ListEntitiesApiV1EntitiesGetParams = {
/**
 * Recherche texte (nom, prénom, entreprise, téléphone, email, CNI)
 */
search?: string | null;
/**
 * Filtrer par type
 */
type?: string | null;
/**
 * Filtrer par sous-type
 */
subtype?: string | null;
/**
 * Filtrer par statut
 */
status?: string | null;
/**
 * A un téléphone
 */
has_phone?: boolean | null;
/**
 * A un email
 */
has_email?: boolean | null;
/**
 * Est une entreprise
 */
has_company?: boolean | null;
/**
 * Type document (cni, passport, rc, nif, rcs, autre)
 */
id_document_type?: string | null;
/**
 * Numéro document
 */
id_document_number?: string | null;
/**
 * @minimum 1
 * @maximum 200
 */
limit?: number;
/**
 * @minimum 0
 */
offset?: number;
/**
 * @pattern ^(created_at|updated_at|last_name|first_name|company_name|display_name)$
 */
order_by?: string;
descending?: boolean;
};
