/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

export type ListTenantsApiV1TenantsGetParams = {
/**
 * Recherche texte
 */
search?: string | null;
/**
 * Filtrer par propriété
 */
property_id?: string | null;
/**
 * @minimum 1
 * @maximum 200
 */
limit?: number;
/**
 * @minimum 0
 */
offset?: number;
};
