/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */
import type { AttestationSummary } from './attestationSummary';
import type { LotResponseGpsBornage } from './lotResponseGpsBornage';
import type { LotResponseHierarchy } from './lotResponseHierarchy';
import type { LotResponseProprietaireClient } from './lotResponseProprietaireClient';

export interface LotResponse {
  /**
     * @minLength 1
     * @maxLength 50
     */
  numero_lot: string;
  /** @exclusiveMinimum 0 */
  superficie: number;
  prix?: number | null;
  /** @pattern ^(actif|vendu|litige|reserve|annule|archive)$ */
  statut?: string;
  proprietaire_client_id?: string | null;
  proprietaire_nom?: string | null;
  proprietaire_prenom?: string | null;
  proprietaire_naissance_date?: string | null;
  proprietaire_naissance_lieu?: string | null;
  proprietaire_cni_numero?: string | null;
  proprietaire_cni_date?: string | null;
  proprietaire_cni_lieu?: string | null;
  proprietaire_profession?: string | null;
  proprietaire_telephone?: string | null;
  proprietaire_email?: string | null;
  gps_lat?: number | null;
  gps_lng?: number | null;
  gps_precision?: number | null;
  gps_bornage?: LotResponseGpsBornage;
  chef_village?: string | null;
  arrete_prefectoral?: string | null;
  arrete_date?: string | null;
  publier_sur_vitrine?: boolean;
  date_cession?: string | null;
  prix_cession?: number | null;
  notes?: string | null;
  id: string;
  ilot_id: string;
  reference: string;
  row_version: number;
  created_at: string;
  updated_at: string;
  deleted_at?: string | null;
  deleted_by?: string | null;
  deleted_reason?: string | null;
  client_updated_at?: string | null;
  last_modified_device_id?: string | null;
  retention_until?: string | null;
  created_by?: string | null;
  updated_by?: string | null;
  hierarchy?: LotResponseHierarchy;
  proprietaire_client?: LotResponseProprietaireClient;
  attestations?: AttestationSummary[] | null;
}
