/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */
import type { EntityResponse } from './entityResponse';

export interface PaginatedEntityResponse {
  items: EntityResponse[];
  total: number;
  limit: number;
  offset: number;
  has_more: boolean;
}
