/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

export interface ProductCreateRequest {
  designation?: string | null;
  nom?: string | null;
  categorie?: string | null;
  prix_unitaire?: number | null;
  stock_actuel?: number | null;
  stock_minimum?: number | null;
  unite?: string | null;
  description?: string | null;
  image_url?: string | null;
}
