/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

export interface ProjectResponse {
  id: string;
  nom: string;
  client_id?: string | null;
  localisation?: string | null;
  type_projet?: string | null;
  budget?: number | null;
  date_debut?: string | null;
  date_fin?: string | null;
  description?: string | null;
  statut: string;
  notes?: string | null;
  cover_image_url?: string | null;
  created_at?: unknown | null;
  updated_at?: unknown | null;
}
