/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */
import type { PropertyResponseProprietaire } from './propertyResponseProprietaire';

export interface PropertyResponse {
  type_bien?: string | null;
  adresse?: string | null;
  proprietaire_name?: string | null;
  valeur?: number | null;
  loyer_mensuel?: number | null;
  charges_mensuelles?: number | null;
  statut?: string | null;
  description?: string | null;
  cover_image_url?: string | null;
  id: string;
  created_at: string;
  updated_at: string;
  created_by?: string | null;
  updated_by?: string | null;
  deleted_at?: string | null;
  proprietaire?: PropertyResponseProprietaire;
}
