/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

export interface RentPaymentStatsResponse {
  total_payments: number;
  paye: number;
  en_attente: number;
  retard: number;
  partiel: number;
  total_amount_collected: number;
  total_amount_pending: number;
  total_amount_late: number;
}
