/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */
import type { RentPaymentResponseContract } from './rentPaymentResponseContract';
import type { RentPaymentResponseLocataire } from './rentPaymentResponseLocataire';
import type { RentPaymentResponseProperty } from './rentPaymentResponseProperty';

export interface RentPaymentResponse {
  locataire_id?: string | null;
  property_id?: string | null;
  contract_id?: string | null;
  montant?: number | null;
  date_paiement?: string | null;
  date_echeance?: string | null;
  mois_concerne?: string | null;
  mode_paiement?: string | null;
  statut?: string | null;
  notes?: string | null;
  reference?: string | null;
  last_document_type?: string | null;
  last_document_at?: string | null;
  last_document_by?: string | null;
  id: string;
  created_at: string;
  updated_at: string;
  created_by?: string | null;
  updated_by?: string | null;
  deleted_at?: string | null;
  property?: RentPaymentResponseProperty;
  contract?: RentPaymentResponseContract;
  locataire?: RentPaymentResponseLocataire;
}
