/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

/**
 * Requête pour upsert single
 */
export interface SettingKeyRequest {
  /**
     * @minLength 1
     * @maxLength 100
     */
  key: string;
  value?: unknown;
}
