/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

/**
 * Réponse pour l'audit
 */
export interface SettingsAuditResponse {
  id: string;
  setting_key: string;
  old_value?: unknown;
  new_value?: unknown;
  changed_by?: string | null;
  changed_at?: string | null;
  action: string;
}
