/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */
import type { SettingsRowValidationSchema } from './settingsRowValidationSchema';

/**
 * Ligne de paramètre pour requête bulk
 */
export interface SettingsRow {
  /**
     * @minLength 1
     * @maxLength 100
     */
  key: string;
  value?: unknown;
  value_type?: string;
  category?: string;
  description?: string | null;
  is_public?: boolean;
  is_editable?: boolean;
  validation_schema?: SettingsRowValidationSchema;
  default_value?: unknown | null;
}
