/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */
import type { SettingsResponseValidationSchema } from './settingsResponseValidationSchema';

/**
 * Réponse pour un paramètre
 */
export interface SettingsResponse {
  key: string;
  value: unknown;
  value_type: string;
  category: string;
  description?: string | null;
  is_public: boolean;
  is_editable: boolean;
  validation_schema?: SettingsResponseValidationSchema;
  default_value?: unknown | null;
  updated_at?: string | null;
}
