/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */
import type { SyncQueueItemPayload } from './syncQueueItemPayload';

export interface SyncQueueItem {
  id: string;
  op: string;
  payload: SyncQueueItemPayload;
  client_updated_at: string;
  status: string;
  attempts: number;
  last_error?: string | null;
}
