/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

export interface TaskUpdateRequest {
  titre?: string | null;
  description?: string | null;
  employee_id?: string | null;
  project_id?: string | null;
  statut?: string | null;
  priorite?: string | null;
  date_debut?: string | null;
  date_echeance?: string | null;
}
