/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

export interface TemoinCreate {
  /**
     * @minLength 2
     * @maxLength 255
     */
  nom: string;
  /**
     * @minLength 2
     * @maxLength 255
     */
  prenom: string;
  profession?: string | null;
  telephone?: string | null;
  cni?: string | null;
}
