/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * EGS Local API
 * OpenAPI spec version: 0.2.0
 */

export interface UpdateUserRequest {
  full_name?: string | null;
  role?: string | null;
  access_level?: string | null;
  poste?: string | null;
  department?: string | null;
  phone?: string | null;
  avatar_url?: string | null;
}
